import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseFrontmatter, renderMarkdown } from "./markdown.mjs";

const projectDir = fileURLToPath(new URL("../", import.meta.url));
const contentDir = resolve(projectDir, "content");
const canonicalBase = "https://mingxiangbian.github.io/NeuroScience/projects/zaji/";
const generatedMarker = "<!-- Generated by projects/zaji/scripts/build-site.mjs; do not edit directly. -->";
const checkOnly = process.argv.includes("--check");

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function toArray(value) {
  if (Array.isArray(value)) return value.map(String).map((item) => item.trim()).filter(Boolean);
  return value ? [String(value).trim()] : [];
}

function validateDate(value, label) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${label} must use YYYY-MM-DD`);
  const [year, month, day] = value.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (date.getUTCFullYear() !== year || date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day) {
    throw new Error(`${label} is not a real calendar date`);
  }
}

function formatDate(value, style = "short") {
  const [year, month, day] = value.split("-").map(Number);
  if (style === "year") return String(year);
  if (style === "long") return `${year} 年 ${month} 月 ${day} 日`;
  return `${year}.${String(month).padStart(2, "0")}.${String(day).padStart(2, "0")}`;
}

function readCollection(type) {
  const dir = resolve(contentDir, type);
  const files = readdirSync(dir)
    .filter((name) => extname(name) === ".md")
    .sort((a, b) => a.localeCompare(b));
  const seenSlugs = new Set();

  return files.map((fileName) => {
    const slug = basename(fileName, ".md");
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`${fileName}: invalid slug`);
    if (seenSlugs.has(slug)) throw new Error(`${fileName}: duplicate slug ${slug}`);
    seenSlugs.add(slug);

    const source = readFileSync(resolve(dir, fileName), "utf8");
    const { frontmatter, body } = parseFrontmatter(source);
    for (const field of ["title", "date", "summary"]) {
      if (!String(frontmatter[field] ?? "").trim()) throw new Error(`${fileName}: missing ${field}`);
    }
    if (/^#\s+/m.test(body)) throw new Error(`${fileName}: body headings must start at ##`);
    if (!body.trim()) throw new Error(`${fileName}: body must not be empty`);
    validateDate(frontmatter.date, `${fileName}: date`);
    if (frontmatter.updated) validateDate(frontmatter.updated, `${fileName}: updated`);

    const record = {
      type,
      slug,
      title: frontmatter.title.trim(),
      date: frontmatter.date,
      updated: frontmatter.updated?.trim() || "",
      summary: frontmatter.summary.trim(),
      tags: toArray(frontmatter.tags),
      body: body.trim(),
      relatedWorks: toArray(frontmatter.related_works),
      relatedPosts: toArray(frontmatter.related_posts),
      status: frontmatter.status?.trim() || "",
      artifactType: frontmatter.type?.trim() || "",
      cover: frontmatter.cover?.trim() || "",
      coverAlt: frontmatter.cover_alt?.trim() || "",
      liveUrl: frontmatter.live_url?.trim() || "",
      sourceUrl: frontmatter.source_url?.trim() || "",
    };

    if (type === "works") {
      for (const field of ["status", "artifactType", "cover", "coverAlt", "liveUrl", "sourceUrl"]) {
        if (!record[field]) throw new Error(`${fileName}: missing ${field}`);
      }
      if (!/^assets\/[a-z0-9][a-z0-9._/-]*$/i.test(record.cover) || record.cover.includes("..")) {
        throw new Error(`${fileName}: cover must be a site-root assets/ path`);
      }
      if (!existsSync(resolve(projectDir, record.cover))) throw new Error(`${fileName}: cover does not exist: ${record.cover}`);
    }

    const plainText = renderMarkdown(record.body).text;
    record.readingMinutes = Math.max(1, Math.ceil(plainText.length / 500));
    return record;
  }).sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
}

function assertRelations(blogs, works) {
  const blogSlugs = new Set(blogs.map((item) => item.slug));
  const workSlugs = new Set(works.map((item) => item.slug));
  for (const blog of blogs) {
    for (const slug of blog.relatedWorks) {
      if (!workSlugs.has(slug)) throw new Error(`${blog.slug}: unknown related work ${slug}`);
    }
  }
  for (const work of works) {
    for (const slug of work.relatedPosts) {
      if (!blogSlugs.has(slug)) throw new Error(`${work.slug}: unknown related post ${slug}`);
    }
  }
}

function resolveSiteHref(value, siteRoot) {
  if (/^(?:https?:\/\/|mailto:|#|\/)/i.test(value)) return value;
  return `${siteRoot}/${value}`;
}

function renderTags(tags) {
  if (tags.length === 0) return "";
  return `<ul class="tag-list" aria-label="标签">${tags.map((tag) => `<li>${escapeHtml(tag)}</li>`).join("")}</ul>`;
}

function renderHead({ title, description, siteRoot, canonicalPath = "", hasMath = false, structuredData = null }) {
  const pageTitle = title === "札记" ? "札记" : `${title} · 札记`;
  const canonical = `${canonicalBase}${canonicalPath}`;
  const mathStyles = hasMath
    ? '\n    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" />'
    : "";
  const jsonLd = structuredData
    ? `\n    <script type="application/ld+json">${JSON.stringify(structuredData).replaceAll("<", "\\u003c")}</script>`
    : "";
  return `${generatedMarker}
<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(pageTitle)}</title>
    <meta name="description" content="${escapeHtml(description)}" />
    <meta name="theme-color" content="#f7f9f9" />
    <meta name="color-scheme" content="light" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="${escapeHtml(pageTitle)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${escapeHtml(canonical)}" />
    <link rel="canonical" href="${escapeHtml(canonical)}" />
    <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%23f7f9f9'/%3E%3Ccircle cx='32' cy='32' r='10' fill='%23df3047'/%3E%3C/svg%3E" />${mathStyles}
    <link rel="stylesheet" href="${siteRoot}/assets/zaji.css" />${jsonLd}
  </head>`;
}

function renderHeader(siteRoot, active) {
  const navItems = [
    ["home", "首页", `${siteRoot}/`],
    ["blog", "博客", `${siteRoot}/blog/`],
    ["works", "成果", `${siteRoot}/works/`],
    ["about", "关于", `${siteRoot}/#about`],
  ];
  return `<a class="skip-link" href="#main-content">跳到正文</a>
    <header class="site-header">
      <div class="header-inner">
        <a class="site-brand" href="${siteRoot}/" aria-label="札记首页"><span aria-hidden="true"></span>札记</a>
        <nav class="site-nav" aria-label="主导航">
          ${navItems.map(([id, label, href]) => `<a href="${href}"${active === id ? ' aria-current="page"' : ""}>${label}</a>`).join("\n          ")}
        </nav>
        <a class="project-return" href="${siteRoot}/../">项目目录 <span aria-hidden="true">↗</span></a>
      </div>
    </header>`;
}

function renderFooter(siteRoot) {
  return `<footer class="site-footer">
      <p><span class="footer-signal" aria-hidden="true"></span>公开、持续、允许修正。</p>
      <p>Markdown 内容源 · Agent 辅助发布 · <a href="${siteRoot}/../">返回项目目录</a></p>
    </footer>`;
}

function renderDocument({
  title,
  description,
  siteRoot,
  canonicalPath,
  active,
  page,
  content,
  hasMath = false,
  progress = false,
  structuredData = null,
}) {
  const mathScript = hasMath
    ? '\n    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>'
    : "";
  const progressHtml = progress
    ? '    <div class="reading-progress" aria-hidden="true"><span></span></div>\n'
    : "";
  return `${renderHead({ title, description, siteRoot, canonicalPath, hasMath, structuredData })}
  <body data-page="${page}">
${progressHtml}    ${renderHeader(siteRoot, active)}
    <main id="main-content">${content}</main>
    ${renderFooter(siteRoot)}${mathScript}
    <script type="module" src="${siteRoot}/assets/zaji.js"></script>
  </body>
</html>
`;
}

function renderBlogRow(blog, siteRoot) {
  return `<article class="blog-row">
          <time datetime="${blog.date}">${formatDate(blog.date)}</time>
          <div class="blog-row-main">
            <h3><a href="${siteRoot}/blog/${blog.slug}/">${escapeHtml(blog.title)}</a></h3>
            <p>${escapeHtml(blog.summary)}</p>
            ${renderTags(blog.tags)}
          </div>
          <a class="row-arrow" href="${siteRoot}/blog/${blog.slug}/" aria-label="阅读《${escapeHtml(blog.title)}》">↗</a>
        </article>`;
}

function renderHome(blogs, works) {
  const siteRoot = ".";
  const latestBlog = blogs[0];
  const latestWorks = works.slice(0, 3);
  const signalDots = [...blogs, ...works]
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, 6)
    .map((_, index, items) => {
      const x = items.length === 1 ? 500 : 120 + (index * 760) / (items.length - 1);
      const y = index % 2 === 0 ? 112 : 92;
      return `<circle cx="${x}" cy="${y}" r="5" />`;
    }).join("");

  const workBand = latestWorks.map((work) => `<a class="work-band-item" href="./works/${work.slug}/">
            <img src="./${work.cover}" alt="${escapeHtml(work.coverAlt)}" width="1200" height="720" loading="lazy" decoding="async" />
            <span class="work-band-copy"><strong>${escapeHtml(work.title)}</strong><small>${escapeHtml(work.artifactType)} · ${escapeHtml(work.status)}</small></span>
            <span class="work-band-arrow" aria-hidden="true">↗</span>
          </a>`).join("");

  const content = `<section class="home-hero" aria-labelledby="home-title">
        <div class="atmosphere" aria-hidden="true"></div>
        <svg class="hero-signal" viewBox="0 0 1000 220" preserveAspectRatio="none" aria-hidden="true">
          <path d="M20 116 C105 116 126 68 210 98 S360 142 434 106 S568 55 642 94 S782 152 980 98" />
          ${signalDots}
        </svg>
        <div class="hero-copy">
          <p class="eyebrow">PUBLIC NOTEBOOK / ${formatDate(latestBlog.date, "year")}</p>
          <h1 id="home-title">札记</h1>
          <p class="hero-intro">记录学习、思考与做过的东西。<br />公开，持续，允许修正。</p>
          <div class="text-actions">
            <a href="./blog/${latestBlog.slug}/">读最新一篇 <span aria-hidden="true">→</span></a>
            <a href="./works/">查看全部成果 <span aria-hidden="true">→</span></a>
          </div>
          <p class="content-count"><span>${blogs.length}</span> 篇博客 <i aria-hidden="true"></i> <span>${works.length}</span> 项成果</p>
        </div>
        <a class="reading-lens" href="./blog/${latestBlog.slug}/" aria-label="正在阅读：${escapeHtml(latestBlog.title)}">
          <span class="lens-kicker"><i aria-hidden="true"></i> 正在阅读</span>
          <strong>${escapeHtml(latestBlog.title)}</strong>
          <span class="lens-summary">${escapeHtml(latestBlog.summary)}</span>
          <span class="lens-meta">${formatDate(latestBlog.date)} · ${latestBlog.readingMinutes} 分钟</span>
          <span class="lens-arrow" aria-hidden="true">↗</span>
        </a>
      </section>

      <section class="home-section latest-writing" aria-labelledby="latest-writing-title">
        <div class="section-heading">
          <div><p class="eyebrow">WRITING</p><h2 id="latest-writing-title">博客</h2></div>
          <a href="./blog/">全部文章 <span aria-hidden="true">→</span></a>
        </div>
        <div class="open-list">${blogs.slice(0, 4).map((blog) => renderBlogRow(blog, ".")).join("\n")}</div>
      </section>

      <section class="home-section home-works" aria-labelledby="home-works-title">
        <div class="section-heading">
          <div><p class="eyebrow">MADE WHILE LEARNING</p><h2 id="home-works-title">成果</h2></div>
          <a href="./works/">全部成果 <span aria-hidden="true">→</span></a>
        </div>
        <div class="work-band">${workBand}</div>
      </section>

      <section class="about-block" id="about" aria-labelledby="about-title">
        <p class="eyebrow">ABOUT THIS PLACE</p>
        <h2 id="about-title">这不是荣誉陈列。</h2>
        <div class="about-copy">
          <p>“成果”指学习过程中真正做过的东西：研究框架、阅读器、实验、工具与阶段性作品。它们可以继续变化，也可以公开保留不完整之处。</p>
          <p>内容以 Markdown 保存，由 Agent 辅助整理、构建和发布。数学表达使用 LaTeX 语法；页面本身保持为可直接访问的静态 HTML。</p>
        </div>
      </section>`;

  return renderDocument({
    title: "札记",
    description: "记录学习、思考与做过的东西。公开、持续、允许修正。",
    siteRoot,
    active: "home",
    page: "zaji-home",
    content,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "Blog",
      name: "札记",
      url: canonicalBase,
      description: "记录学习、思考与做过的东西。",
      inLanguage: "zh-CN",
    },
  });
}

function groupBlogsByYear(blogs) {
  const groups = new Map();
  for (const blog of blogs) {
    const year = formatDate(blog.date, "year");
    if (!groups.has(year)) groups.set(year, []);
    groups.get(year).push(blog);
  }
  return groups;
}

function renderBlogIndex(blogs) {
  const siteRoot = "..";
  const groups = [...groupBlogsByYear(blogs)].map(([year, items]) => `<section class="year-group" aria-labelledby="year-${year}">
          <h2 id="year-${year}">${year}</h2>
          <div class="chronology-list">${items.map((blog) => renderBlogRow(blog, "..")).join("\n")}</div>
        </section>`).join("\n");
  const content = `<header class="page-lead blog-lead">
        <p class="eyebrow">BLOG / ${blogs.length} ENTRIES</p>
        <h1>博客</h1>
        <p>按时间留下问题、理解和修正。文章不是结论仓库，而是思考如何变化的可追溯记录。</p>
      </header>
      <div class="chronology" aria-label="博客时间线"><span class="chronology-signal" aria-hidden="true"></span>${groups}</div>`;
  return renderDocument({
    title: "博客",
    description: "札记的公开博客，按时间记录学习、思考与修正。",
    siteRoot,
    canonicalPath: "blog/",
    active: "blog",
    page: "zaji-blog-index",
    content,
  });
}

function renderToc(toc, className = "article-toc-list") {
  if (toc.length === 0) return "";
  return `<ol class="${className}">${toc.map((item) => `<li data-depth="${item.depth}"><a href="#${escapeHtml(item.id)}">${escapeHtml(item.title)}</a></li>`).join("")}</ol>`;
}

function renderRelatedWorks(slugs, works, siteRoot) {
  const related = slugs.map((slug) => works.find((work) => work.slug === slug)).filter(Boolean);
  if (related.length === 0) return "";
  return `<section class="related-block" aria-labelledby="related-works-title">
        <div class="section-heading"><div><p class="eyebrow">CONNECTED WORK</p><h2 id="related-works-title">相关成果</h2></div></div>
        <div class="related-open-list">${related.map((work) => `<a href="${siteRoot}/works/${work.slug}/"><span>${escapeHtml(work.artifactType)}</span><strong>${escapeHtml(work.title)}</strong><i aria-hidden="true">↗</i></a>`).join("")}</div>
      </section>`;
}

function renderBlogArticle(blog, blogs, works) {
  const siteRoot = "../..";
  const rendered = renderMarkdown(blog.body, { siteRoot });
  const index = blogs.findIndex((item) => item.slug === blog.slug);
  const newer = index > 0 ? blogs[index - 1] : null;
  const older = index < blogs.length - 1 ? blogs[index + 1] : null;
  const updatedMeta = blog.updated
    ? `              <div><dt>更新</dt><dd><time datetime="${blog.updated}">${formatDate(blog.updated, "long")}</time></dd></div>\n`
    : "";
  const nav = newer || older ? `<nav class="entry-nav" aria-label="相邻文章">
        ${older ? `<a href="../${older.slug}/"><span>上一篇</span><strong>${escapeHtml(older.title)}</strong></a>` : "<span></span>"}${newer ? `
        <a href="../${newer.slug}/"><span>下一篇</span><strong>${escapeHtml(newer.title)}</strong></a>` : ""}
      </nav>` : "";
  const toc = renderToc(rendered.toc);
  const content = `<article class="article-page">
        <header class="article-hero">
          <a class="back-link" href="../">← 返回博客</a>
          <p class="eyebrow">NOTE / ${formatDate(blog.date)}</p>
          <h1>${escapeHtml(blog.title)}</h1>
          <p class="article-deck">${escapeHtml(blog.summary)}</p>
          ${renderTags(blog.tags)}
        </header>
        <div class="mobile-toc">${toc ? `<details><summary>本文目录</summary>${renderToc(rendered.toc, "mobile-toc-list")}</details>` : ""}</div>
        <div class="article-layout">
          <aside class="article-meta" aria-label="文章信息">
            <dl>
              <div><dt>发布</dt><dd><time datetime="${blog.date}">${formatDate(blog.date, "long")}</time></dd></div>
${updatedMeta}              <div><dt>阅读</dt><dd>约 ${blog.readingMinutes} 分钟</dd></div>
            </dl>
          </aside>
          <div class="prose article-prose">${rendered.html}</div>
          <aside class="article-toc" aria-label="本文目录"><p>目录</p>${toc}</aside>
        </div>
      </article>
      ${renderRelatedWorks(blog.relatedWorks, works, siteRoot)}
      ${nav}`;

  return renderDocument({
    title: blog.title,
    description: blog.summary,
    siteRoot,
    canonicalPath: `blog/${blog.slug}/`,
    active: "blog",
    page: "zaji-blog-article",
    content,
    hasMath: rendered.hasMath,
    progress: true,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      headline: blog.title,
      description: blog.summary,
      datePublished: blog.date,
      ...(blog.updated ? { dateModified: blog.updated } : {}),
      mainEntityOfPage: `${canonicalBase}blog/${blog.slug}/`,
      inLanguage: "zh-CN",
    },
  });
}

function renderWorksIndex(works) {
  const siteRoot = "..";
  const first = works[0];
  const list = works.map((work, index) => `<a class="work-list-item${index === 0 ? " is-current" : ""}" href="./${work.slug}/"
            data-preview-src="../${work.cover}"
            data-preview-alt="${escapeHtml(work.coverAlt)}"
            data-preview-title="${escapeHtml(work.title)}"
            data-preview-meta="${escapeHtml(`${work.artifactType} · ${work.status}`)}"
            data-preview-href="./${work.slug}/">
          <span class="work-list-copy"><small>${escapeHtml(work.artifactType)} · ${formatDate(work.date)}</small><strong>${escapeHtml(work.title)}</strong><em>${escapeHtml(work.summary)}</em>${renderTags(work.tags)}</span>
          <img class="work-list-mobile-image" src="../${work.cover}" alt="${escapeHtml(work.coverAlt)}" width="1200" height="720" loading="lazy" decoding="async" />
          <span class="row-arrow" aria-hidden="true">↗</span>
        </a>`).join("\n");
  const content = `<header class="page-lead works-lead">
        <p class="eyebrow">WORKS / ${works.length} ARTIFACTS</p>
        <h1>成果</h1>
        <p>不是获奖记录，而是学习过程中真正做过、仍可打开查看的东西。</p>
      </header>
      <div class="works-workbench">
        <div class="works-list" aria-label="成果列表">${list}</div>
        <aside class="work-preview-lens" aria-live="polite">
          <div class="preview-image-wrap"><img src="../${first.cover}" alt="${escapeHtml(first.coverAlt)}" width="1200" height="720" /></div>
          <p>当前选择</p>
          <strong>${escapeHtml(first.title)}</strong>
          <span>${escapeHtml(first.artifactType)} · ${escapeHtml(first.status)}</span>
          <a href="./${first.slug}/">查看记录 <span aria-hidden="true">↗</span></a>
        </aside>
      </div>`;
  return renderDocument({
    title: "成果",
    description: "学习过程中做过的研究框架、阅读器、实验、工具与阶段性作品。",
    siteRoot,
    canonicalPath: "works/",
    active: "works",
    page: "zaji-works-index",
    content,
  });
}

function renderRelatedPosts(slugs, blogs, siteRoot) {
  const related = slugs.map((slug) => blogs.find((blog) => blog.slug === slug)).filter(Boolean);
  if (related.length === 0) return "";
  return `<section class="related-block" aria-labelledby="related-posts-title">
        <div class="section-heading"><div><p class="eyebrow">RELATED WRITING</p><h2 id="related-posts-title">相关博客</h2></div></div>
        <div class="related-open-list">${related.map((blog) => `<a href="${siteRoot}/blog/${blog.slug}/"><span>${formatDate(blog.date)}</span><strong>${escapeHtml(blog.title)}</strong><i aria-hidden="true">↗</i></a>`).join("")}</div>
      </section>`;
}

function renderWorkDetail(work, works, blogs) {
  const siteRoot = "../..";
  const rendered = renderMarkdown(work.body, { siteRoot });
  const index = works.findIndex((item) => item.slug === work.slug);
  const newer = index > 0 ? works[index - 1] : null;
  const older = index < works.length - 1 ? works[index + 1] : null;
  const updatedFact = work.updated
    ? `              <div><dt>最近更新</dt><dd><time datetime="${work.updated}">${formatDate(work.updated, "long")}</time></dd></div>\n`
    : "";
  const nav = newer || older ? `<nav class="entry-nav" aria-label="相邻成果">
        ${older ? `<a href="../${older.slug}/"><span>上一个成果</span><strong>${escapeHtml(older.title)}</strong></a>` : "<span></span>"}${newer ? `
        <a href="../${newer.slug}/"><span>下一个成果</span><strong>${escapeHtml(newer.title)}</strong></a>` : ""}
      </nav>` : "";
  const content = `<article class="work-detail">
        <a class="back-link" href="../">← 返回成果</a>
        <header class="work-detail-hero">
          <div class="work-detail-copy">
            <p class="eyebrow">${escapeHtml(work.artifactType)} / ${escapeHtml(work.status)}</p>
            <h1>${escapeHtml(work.title)}</h1>
            <p>${escapeHtml(work.summary)}</p>
            <div class="text-actions">
              <a href="${escapeHtml(resolveSiteHref(work.liveUrl, siteRoot))}">打开成果 <span aria-hidden="true">↗</span></a>
              <a href="${escapeHtml(resolveSiteHref(work.sourceUrl, siteRoot))}">查看源文件 <span aria-hidden="true">↗</span></a>
            </div>
            <dl class="work-facts">
              <div><dt>类型</dt><dd>${escapeHtml(work.artifactType)}</dd></div>
              <div><dt>状态</dt><dd>${escapeHtml(work.status)}</dd></div>
              <div><dt>开始记录</dt><dd><time datetime="${work.date}">${formatDate(work.date, "long")}</time></dd></div>
${updatedFact}            </dl>
          </div>
          <figure class="work-hero-media"><img src="${siteRoot}/${work.cover}" alt="${escapeHtml(work.coverAlt)}" width="1200" height="720" /><figcaption>真实页面截取 · ${escapeHtml(work.title)}</figcaption></figure>
        </header>
        <div class="work-story">
          <aside aria-label="成果标签">${renderTags(work.tags)}</aside>
          <div class="prose work-prose">${rendered.html}</div>
        </div>
      </article>
      ${renderRelatedPosts(work.relatedPosts, blogs, siteRoot)}
      ${nav}`;
  return renderDocument({
    title: work.title,
    description: work.summary,
    siteRoot,
    canonicalPath: `works/${work.slug}/`,
    active: "works",
    page: "zaji-work-detail",
    content,
    hasMath: rendered.hasMath,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "CreativeWork",
      name: work.title,
      description: work.summary,
      dateCreated: work.date,
      ...(work.updated ? { dateModified: work.updated } : {}),
      url: `${canonicalBase}works/${work.slug}/`,
      inLanguage: "zh-CN",
    },
  });
}

function collectExistingDetailPages(type) {
  const dir = resolve(projectDir, type);
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(resolve(dir, entry.name, "index.html")))
    .map((entry) => `${type}/${entry.name}/index.html`);
}

function buildExpectedPages(blogs, works) {
  const pages = new Map([
    ["index.html", renderHome(blogs, works)],
    ["blog/index.html", renderBlogIndex(blogs)],
    ["works/index.html", renderWorksIndex(works)],
  ]);
  for (const blog of blogs) pages.set(`blog/${blog.slug}/index.html`, renderBlogArticle(blog, blogs, works));
  for (const work of works) pages.set(`works/${work.slug}/index.html`, renderWorkDetail(work, works, blogs));
  return pages;
}

function syncPages(pages) {
  const errors = [];
  for (const [relativePath, expected] of pages) {
    const outputPath = resolve(projectDir, relativePath);
    if (checkOnly) {
      if (!existsSync(outputPath)) errors.push(`${relativePath} is missing`);
      else if (readFileSync(outputPath, "utf8") !== expected) errors.push(`${relativePath} is out of date`);
      continue;
    }
    mkdirSync(dirname(outputPath), { recursive: true });
    if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== expected) writeFileSync(outputPath, expected);
  }

  const expectedPaths = new Set(pages.keys());
  for (const path of [...collectExistingDetailPages("blog"), ...collectExistingDetailPages("works")]) {
    if (!expectedPaths.has(path)) errors.push(`${path} is stale; remove it explicitly`);
  }
  if (errors.length > 0) throw new Error(errors.join("\n"));
}

const blogs = readCollection("blog");
const works = readCollection("works");
if (blogs.length === 0) throw new Error("札记至少需要一篇真实博客文章");
if (works.length === 0) throw new Error("札记至少需要一项真实成果");
assertRelations(blogs, works);
const pages = buildExpectedPages(blogs, works);
syncPages(pages);
console.log(checkOnly ? `Zaji check passed: ${pages.size} generated pages are current.` : `Zaji built: ${pages.size} static pages.`);
